"""add_monitor_type_and_expected_status_codes

Revision ID: 541a33aa1019
Revises: 5d29679cc252
Create Date: 2026-07-05 16:04:53.324926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '541a33aa1019'
down_revision: Union[str, Sequence[str], None] = '5d29679cc252'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_integrations_id'), table_name='integrations')
    op.drop_table('integrations')
    
    # Correctly indented with server_default
    op.add_column(
        'monitors', 
        sa.Column(
            'monitor_type', 
            sa.Enum('STANDARD', 'SECURE_EDGE', name='monitortype'), 
            nullable=False, 
            server_default='STANDARD'
        )
    )
    
    # Added server_default here to prevent a second NotNullViolationError
    op.add_column(
        'monitors', 
        sa.Column(
            'expected_status_codes', 
            sa.JSON(), 
            nullable=False, 
            server_default='[200]'
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('monitors', 'expected_status_codes')
    op.drop_column('monitors', 'monitor_type')
    
    # Drop the enum type when rolling back so it doesn't clutter PostgreSQL
    bind = op.get_bind()
    sa.Enum(name='monitortype').drop(bind, checkfirst=True)
    
    op.create_table(
        'integrations',
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column('channel_type', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('webhook_url', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('integrations_user_id_fkey'), ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id', name=op.f('integrations_pkey'))
    )
    op.create_index(op.f('ix_integrations_id'), 'integrations', ['id'], unique=False)
    # ### end Alembic commands ###